#!/bin/bash

set -euo pipefail

function diff() {
    local f1=data/$1-glyphs.txt
    local f2=data/$2-glyphs.txt
    echo Added
    comm -13 <(cut -d ' ' -f 1 "$f1") <(cut -d ' ' -f 1 "$f2")
    echo
    echo Removed
    comm -23 <(cut -d ' ' -f 1 "$f1") <(cut -d ' ' -f 1 "$f2")
}

function diffText() {
    diff "$1" "$2" | python codepoints2text.py
}

function available() {
    local codepoints
    codepoints=$(echo "$1" | python text2codepoints.py)
    local result
    result=$(_availableImpl "$(echo a | python text2codepoints.py)")
    for cp in $codepoints; do
        local thisResult
        thisResult=$(_availableImpl "$cp")
        result=$(echo "$result" "$thisResult" | tr ' ' '\n' | sort | uniq -d)
    done
    echo "$result" | tr ' ' '\n'
}

function _availableImpl() {
    local f
    grep -l "$1" data/*-glyphs.txt | while IFS= read -r f; do
        f=${f##*/}
        f=${f%%-*}
        echo "$f"
    done
}

if (($# == 0)); then
    cat <<EOF
Usage: $(basename "$0") COMMAND [ARGS...]

Commands:
    diff PLATFORM1 PLATFORM2
         List glyphs available in just one of the specified platforms, in
         U+xxxxxx format
    diffText PLATFORM1 PLATFORM2
         List glyphs available in just one of the specified platforms, as
         plain text
    available TEXT
         List the platforms on which all codepoints in the specified text are
         available
EOF
    exit 1
fi

cmd=$1
shift
$cmd "$@"
