#!/bin/bash

set -euo pipefail

function diff() {
    f1=data/$1-glyphs.txt
    f2=data/$2-glyphs.txt
    cat "$f1" "$f2" | cut -d ' ' -f 1 | sort | uniq -u
}

function diffText() {
    diff "$1" "$2" | python codepoints2text.py
}

function available() {
    codepoints=$(echo "$1" | python text2codepoints.py)
    result=$(_availableImpl "$(echo a | python text2codepoints.py)")
    for cp in $codepoints; do
        thisResult=$(_availableImpl "$cp")
        result=$(echo "$result" "$thisResult" | tr ' ' '\n' | sort | uniq -d)
    done
    echo "$result" | tr ' ' '\n'
}

function _availableImpl() {
    grep -l "$1" data/*-glyphs.txt | while IFS= read -r f; do
        f=${f##*/}
        f=${f%%-*}
        echo "$f"
    done
}

if (($# == 0)); then
    cat <<EOF
Usage: $(basename "$0") COMMAND [ARGS...]

Commands:
    diff PLATFORM1 PLATFORM2
         List glyphs available in just one of the specified platforms, in
         U+xxxxxx format
    diffText PLATFORM1 PLATFORM2
         List glyphs available in just one of the specified platforms, as
         plain text
    available TEXT
         List the platforms on which all codepoints in the specified text are
         available
EOF
    exit 1
fi

cmd=$1
shift
$cmd "$@"
